"""Append approved AutoCorrect2 candidates to the generated include file."""

from __future__ import annotations

from collections.abc import Sequence
from pathlib import Path

from ..core.options import SettingState
from ..file_io import read_text, write_text
from .constants import GENERATED_HOTSTRINGS_RELATIVE_PATH
from .models import AutoCorrect2CandidateHotstring

GENERATED_FILE_HEADER = (
    "; AUTO-GENERATED BY autocorrect2-hotstring-generation\n"
    "; Add this file to AutoCorrect2 with a one-time #Include.\n"
    "; Do not edit generated entries manually.\n"
)
"""Header written when the generated include file is first created."""


def append_candidates(
    candidates: Sequence[AutoCorrect2CandidateHotstring],
    *,
    project_dir: Path,
    relative_path: Path = GENERATED_HOTSTRINGS_RELATIVE_PATH,
) -> Path:
    """Append accepted candidates to the project-owned AutoCorrect2 include.

    Each candidate must explicitly use `B0` and `X`, which are required by the
    AutoCorrect2 `f()`-based generated form. Trigger rendering is delegated to
    the hotstring model, which emits its canonical `ahk_trigger` source form.

    Args:
        candidates:
            Accepted AutoCorrect2 candidates to append.
        project_dir:
            AutoCorrect2 project directory.
        relative_path:
            Generated include path relative to `project_dir`.

    Returns:
        Path of the generated include file.

    Raises:
        ValueError:
            If a candidate is not explicitly configured with `B0X` behavior.
        OSError:
            If the generated file cannot be read or written.
    """
    target_path = project_dir / relative_path
    if not candidates:
        return target_path

    for candidate in candidates:
        _validate_writable_candidate(candidate)

    prefix = ""
    if not target_path.exists() or target_path.stat().st_size == 0:
        prefix = GENERATED_FILE_HEADER
    else:
        current = read_text(target_path)
        if not current.endswith(("\n", "\r")):
            prefix = "\n"

    rendered = "\n".join(candidate.render() for candidate in candidates)
    write_text(target_path, prefix + rendered + "\n", append=True)
    return target_path


def _validate_writable_candidate(candidate: AutoCorrect2CandidateHotstring) -> None:
    """Validate the AutoCorrect2-specific `B0X` writing contract.

    Args:
        candidate:
            Candidate that may be appended to the generated include.

    Raises:
        ValueError:
            If automatic backspacing is not explicitly disabled or execution
            is not explicitly enabled.
    """
    if candidate.options.automatic_backspacing is not SettingState.DISABLED:
        raise ValueError(
            "AutoCorrect2 generated candidates must explicitly disable "
            "automatic backspacing with B0."
        )
    if candidate.options.execute is not SettingState.ENABLED:
        raise ValueError(
            "AutoCorrect2 generated candidates must explicitly enable "
            "executable content handling with X."
        )
